---
- name: Install nvm {{ nvm_version }}
  ansible.builtin.git:
    repo: "{{ nvm_git_repository }}"
    dest: "{{ nvm_install_path }}"
    version: "v{{ nvm_version }}"
    force: "{{ nvm_force_install | bool }}"
  when: nvm_version | regex_search('\\d.')

- name: Install nvm latest
  ansible.builtin.git:
    repo: "{{ nvm_git_repository }}"
    dest: "{{ nvm_install_path }}"
    version: "{% if nvm_version == 'latest' %}master{% else %}{{ nvm_version }}{% endif %}"
    force: "{{ nvm_force_install | bool }}"
  when: nvm_version | regex_search('master|HEAD|latest')

- name: Update ~/.profile to source nvm
  ansible.builtin.blockinfile:
    path: "{{ nvm_shell_init_file }}"
    marker: "# NVM path management from ansible {mark}"
    block: |
      . {{ nvm_install_path }}/nvm.sh
