---
- name: Import RedHat setup
  ansible.builtin.import_tasks: setup-redhat.yml
  when: ansible_os_family == "RedHat" and nvm_install_deps
  tags: nvm

- name: Import Debian setup
  ansible.builtin.import_tasks: setup-debian.yml
  when: ansible_os_family == "Debian" and nvm_install_deps
  tags: nvm

- name: Import NVM install
  ansible.builtin.import_tasks: install_nvm.yml
  tags: nvm

- name: Import Node.js install
  ansible.builtin.import_tasks: install_nodejs.yml
  tags: nvm

- name: Import validation
  ansible.builtin.import_tasks: validate.yml
  tags: nvm

- name: Install pm2
  npm:
    name: pm2
    global: yes
