---
- name: Install dependencies
  become: true
  become_user: root
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - curl
      - build-essential
      - libssl-dev
