---

- name: Laravel Servers
  hosts: localhost
  #  remote_user: ubuntu
  become: yes
  roles:
          #    - common
    - php
    - nginx
    - postgres-master
    - mysql-master
      #    - database
      #    - laravel
